# 服务基本配置
server:
  runMode: release
  port: 9000
  readTimeout: 60
  writeTimeout: 60
  jwtSecret: MDdAEwx7Cs
  jwtExpire: 24   # 单位: 小时
  prefixUrl: http://127.0.0.1:8000
  dbSecret: LGlVCvQhD6evGBa8  #必须是16位、24位、32位其中一种！


# 数据库配置
database:
  dbType: mysql
  connStr: root:Qq1234567@tcp(127.0.0.1:3306)/libra?charset=utf8&parseTime=True&loc=Local
  debug: true

